/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ercom_server_NDKServer */

#ifndef _Included_com_ercom_server_NDKServer
#define _Included_com_ercom_server_NDKServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ercom_server_NDKServer
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ercom_server_NDKServer_getMyString
  (JNIEnv *, jobject);

/*
 * Class:     com_ercom_server_NDKServer
 * Method:    startServer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ercom_server_NDKServer_startServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
