/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_enmingx_client2_NDKClient2 */

#ifndef _Included_com_enmingx_client2_NDKClient2
#define _Included_com_enmingx_client2_NDKClient2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_enmingx_client2_NDKClient2
 * Method:    connectServer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_enmingx_client2_NDKClient2_connectServer
  (JNIEnv *, jobject);

/*
 * Class:     com_enmingx_client2_NDKClient2
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_enmingx_client2_NDKClient2_getMyString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
