/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ercom_socket_NDKClient1 */

#ifndef _Included_com_ercom_socket_NDKClient1
#define _Included_com_ercom_socket_NDKClient1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ercom_socket_NDKClient1
 * Method:    connectServer
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ercom_socket_NDKClient1_connectServer
  (JNIEnv *, jobject);

/*
 * Class:     com_ercom_socket_NDKClient1
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ercom_socket_NDKClient1_getMyString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
